Добавлены основные файлы клиента
MoreliaTalk/morelia_client_qt pull request #1
Opened 2020-10-06 19:03 UTC by ViktoriyaKiroy

Добавлены файлы окон мессенжера в qt(.ui), те же файлы в формате .ру… файл с основной логикой приложения, сервер, на котором это работает(позднее при переводе приложения на основной сервер MoreliaTalk будет удален)

2020-10-07 06:21 UTC, stepanskryabin commented on messenger.py
> +url = 'http://127.0.0.1:5000/'
оформить константы капсом.

2020-10-07 06:23 UTC, stepanskryabin commented on clientui.py
> +        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.852, y2:0.863636, stop:0 rgba(179, 255, 254, 255), stop:1 rgba(255, 216, 246, 255));")
перенести длинную строку

2020-10-07 06:23 UTC, stepanskryabin commented on clientui.py
> +        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; font-weight:600; font-style:italic;\">Мессенжер</span></p></body></html>"))
Перенести длинную строку.

2020-10-07 06:24 UTC, stepanskryabin commented on errorui.py
> +        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Извините, произошла ошибка</p></body></html>"))
Перенести длинную строку.

2020-10-07 06:25 UTC, stepanskryabin commented on user_and_pass.ui
> +   <widget class="QLineEdit" name="lineEdit_2">
Переименовать виджет.

2020-10-07 06:25 UTC, stepanskryabin commented on user_and_pass.ui
> +   <widget class="QLabel" name="label_4">
Переименовать виджет.

2020-10-07 06:26 UTC, stepanskryabin commented on user_and_passui.py
> +        Messenger.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.852, y2:0.863636, stop:0 rgba(179, 255, 254, 255), stop:1 rgba(255, 216, 246, 255));")
Перенести длинную строку.

2020-10-07 06:26 UTC, stepanskryabin commented on user_and_passui.py
> +        self.lineEdit_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.852, y2:0.863636, stop:0 rgb(179, 255, 254), stop:1 rgb(255, 216, 246));")
Перенести длинную строку.

2020-10-07 06:27 UTC, stepanskryabin commented on user_and_passui.py
> +        self.label.setText(_translate("Messenger", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Имя пользователя</span></p></body></html>"))
Перенести длинные строки.

2020-10-07 06:28 UTC, stepanskryabin commented on messenger.py
> +            self.lineEdit.setStyleSheet("background: qlineargradient(spread:pad, x1:0, y1:0, x2:0.852, y2:0.863636, stop:0 rgba(179, 255, 254, 255), stop:1 rgba(255, 216, 246, 255));")
Перенести длинные строки.

2020-10-07 06:29 UTC, stepanskryabin commented on messenger.py
> +    app.exec_()
Зачем тут конструкция tr...except?

2020-10-07 06:30 UTC, stepanskryabin commented on messenger.py
> +        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.852, y2:0.863636, stop:0 rgba(179, 255, 254, 255), stop:1 rgba(255, 216, 246, 255));")
Удасно длинные строки.

2020-10-07 06:32 UTC, stepanskryabin requested changes
Оформить код по PEP8. Сделать перенос длинных строк. Убрать висящие скобочки. Добавить пустую строку вконце каждого *.py файла.

2020-10-07 19:23 UTC, stepanskryabin commented on messenger.py
> +        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.852, y2:0.863636, stop:0 rgba(179, 255, 254, 255), stop:1 rgba(255, 216, 246, 255));")
Я бы это всё перенёс в констранту настройки темы оформления, например:
`DARK_THEME = "color: rgb(255, 255, 255); background-color:  rgba(0, 255, 254, 0);"`

потом заменил бы строку №124:
`self.label.setStyleSheet(DARK_THEME)`

2020-10-08 06:06 UTC, NekrodNIK commented
Поправь всё как сказал @stepanskryabin

2020-10-14 16:29 UTC, stepanskryabin approved these changes

2020-10-16 13:23 UTC, NekrodNIK approved these changes

2020-10-16 13:23 UTC, merged