Полный рефакторинг контроллера чатов
MoreliaTalk/morelia_client_qt pull request #17
Opened 2021-10-16 09:46 UTC by NekrodNIK

- Проведён рефакторинг контроллера чатов. Буквально переписан заново. Теперь эта часть кода понятна и проста. Все манипуляции с изображением аватарки теперь делает библиотека Pillow. Данная библиотека будет использоваться в коде клиента повсеместно при обработке изображений.
- Переписаны тесты для контроллера чата. Теперь их покрытие составляет 100%(судя по отчёту библиотеки coverage.py)
- Мелкие правки и улучшения

2021-10-16 10:16 UTC, rus-ai commented on interfaces/chats_controller.py
> +            elif len(splitName) == 2:
Если там ФИО или даже ФИО Оглы? Нужно не ==2, а > 2
Ну и наверное предусмотреть что отображать, если почему то с бэкэнда придет пустой юзернэйм.

2021-10-16 10:17 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +            elif len(splitName) == 2:
OK. Будет сделано

2021-10-16 10:18 UTC, rus-ai commented on interfaces/chats_controller.py
> +        self.list_chats: list[ChatItem] = list()
А зачем нам все таки отдельный список? Мы же всегда можем в детях ChatContentLayout такой же список взять?

2021-10-16 10:20 UTC, rus-ai commented on interfaces/raw_interfaces/contact_card.py
> +# Form implementation generated from reading ui file 'c:\DJANGO-NIKITA\MoreliaTalk\morelia_client_qt\interfaces\raw_interfaces\ui\contact_card.ui'
Палишься, Никита) лучше pyuic вызывать находясь в папке с интерфейсом

2021-10-16 10:40 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +        self.list_chats: list[ChatItem] = list()
Ага конечно, можем))) Я так же думал. В итоге при вызове children() он возращает пустой список. Понятия не имею по чему, вот и завёл этот список

2021-10-16 10:41 UTC, NekrodNIK commented on interfaces/raw_interfaces/contact_card.py
> +# Form implementation generated from reading ui file 'c:\DJANGO-NIKITA\MoreliaTalk\morelia_client_qt\interfaces\raw_interfaces\ui\contact_card.ui'
Долго переходить, но на заметку возьму)))

2021-10-16 11:06 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +            elif len(splitName) == 2:
готово

2021-10-16 11:07 UTC, NekrodNIK commented on interfaces/raw_interfaces/contact_card.py
> +# Form implementation generated from reading ui file 'c:\DJANGO-NIKITA\MoreliaTalk\morelia_client_qt\interfaces\raw_interfaces\ui\contact_card.ui'
Готово

2021-10-17 04:13 UTC, stepanskryabin commented on Pipfile
> +pillow = "*"
Предлагаю добавить указание на конкретные версии пакетов (всех), а так же перенести flake8 в секцию dev-packages. Для пидантика лучше тоже указать конкретный пакет, чем добавлять его по маске.

2021-10-17 04:19 UTC, stepanskryabin commented on interfaces/raw_interfaces/contact_card.py
> +from PyQt5 import QtCore, QtGui, QtWidgets
QtGui поди убрать? он всё-равно не используется.

2021-10-17 04:20 UTC, stepanskryabin commented on interfaces/raw_interfaces/contact_card.py
> +from PyQt5 import QtCore, QtGui, QtWidgets
в файле main_window.py тоже самое

2021-10-17 04:26 UTC, stepanskryabin commented on main.py
> +from interfaces.raw_interfaces.main_window import Ui_MainWindow
Слишком длинный путь получился, причём несколько раз повторяется interfaces. Можно что-то типа такого:
```python
from ui.main_window import Ui_MainWindow
from controller.chats import ChatsController
from controller.message import MessageController
```

2021-10-17 04:45 UTC, stepanskryabin commented on main.py
>          self.setColorTheme()
Не понял, а зечем вызывать функцию и не передавать в неё параметры?

2021-10-17 04:49 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +from PyQt5.QtCore import Qt
импорт Qt нигде не используется.

2021-10-17 04:56 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +            splitName = chatName.split()
Нужно определиться с именами объектов: или камелкейс или через подчёркивание.

2021-10-17 05:28 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +        super().__init__()
А зачем выызывать __init__ у дочернего класса которого нет?

2021-10-17 05:33 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +                name_initials = "N_I"
Что значит "N_I"?

2021-10-17 05:43 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +                name_initials = splitName[0][0]+splitName[0][1]
можно же проще: splitName[0][0:2]

2021-10-17 05:51 UTC, stepanskryabin commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
Может лучше плюсовать в самом объекте count_up_to ?

2021-10-17 05:53 UTC, stepanskryabin requested changes
Исправить мелкие недоработки и ответить на вопросы)))

2021-10-17 05:55 UTC, NekrodNIK commented on interfaces/raw_interfaces/contact_card.py
> +from PyQt5 import QtCore, QtGui, QtWidgets
Нет смысла, эти файлы сами генерируются, в том же pyside6-uic лишних импортов в 10 раз больше

2021-10-17 05:56 UTC, NekrodNIK commented on main.py
> +from interfaces.raw_interfaces.main_window import Ui_MainWindow
Чуть сокращу, путём переименование папки raw_interfaces просто в raw

2021-10-17 05:57 UTC, NekrodNIK commented on main.py
>          self.setColorTheme()
Значения по умолчанию, если надо меняются, если нет - то нет

2021-10-17 06:00 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +            splitName = chatName.split()
Классы - CamelCase
переменные и файлы - snake_case

2021-10-17 06:01 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +        super().__init__()
Так уже было при @rus-ai, видимо забыл убрать))))

2021-10-17 06:01 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +                name_initials = "N_I"
not image)))

2021-10-17 06:02 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +                name_initials = splitName[0][0]+splitName[0][1]
Можно, просто на момент написания вылетело из головы

2021-10-17 06:02 UTC, NekrodNIK commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
Придираться к тестам?!

2021-10-17 06:07 UTC, stepanskryabin commented on main.py
>          self.setColorTheme()
Так, а в дальнейшем где будут передаваться параметры?

2021-10-17 06:08 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +                name_initials = "N_I"
лучше уж тогда так: o_O

2021-10-17 06:09 UTC, stepanskryabin commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
это я ещё к пробелам не придрался ))

2021-10-17 06:21 UTC, NekrodNIK commented on Pipfile
> +pillow = "*"
Готово

2021-10-17 06:37 UTC, NekrodNIK commented on main.py
>          self.setColorTheme()
При применении кастомной темы, которую пользователь через меню настроек сможет настроить

2021-10-17 06:37 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +                name_initials = "N_I"
))))

2021-10-17 06:38 UTC, NekrodNIK commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
линтер не ругается, значит всё ок))))

2021-10-17 06:44 UTC, stepanskryabin commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
А как же внутреннее чувство прекрасного?

2021-10-17 06:45 UTC, NekrodNIK commented on main.py
> +from interfaces.raw_interfaces.main_window import Ui_MainWindow
Готово

2021-10-17 06:47 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +from PyQt5.QtCore import Qt
Готово

2021-10-17 06:49 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +        super().__init__()
Готово

2021-10-17 06:51 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +                name_initials = "N_I"
Готово

2021-10-17 07:06 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +                name_initials = splitName[0][0]+splitName[0][1]
Готово!

2021-10-17 07:06 UTC, NekrodNIK commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
Это тесты, их пишут в попыхах под конец))) Поправлю сейчас

2021-10-17 07:12 UTC, NekrodNIK commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
> А как же внутреннее чувство прекрасного?

Оно есть, вот к примеру код @rus-ai местами страдает от отсутствие разделения на блоки полотна кода, и если в друг его надо поправить, я его заодно форматирую)))

2021-10-17 07:12 UTC, NekrodNIK commented on tests/test_chat_controller.py
> +        self.assertEqual(self.mainWindow.ContactsContent.count(), count_up_to+1)
Готово

2021-10-17 07:29 UTC, stepanskryabin approved these changes

2021-10-17 07:38 UTC, merged