Добавлено логирование клиента и написан нормальный README.md
MoreliaTalk/morelia_client_qt pull request #18
Opened 2021-10-17 12:53 UTC by NekrodNIK

- добавлено логирование, с помощью библиотеки loguru
- написан README.md

2021-10-17 13:12 UTC, rus-ai commented on interfaces/chats_controller.py
> +        logger.info("add new chat " + new_chat_item)
Как то не единообразно - тут мы объект в лог пихаем, а в месседж печатаем в лог параметры тип и текст. Или мы потом сообщение тоже превратим в отдельный класс и будет потом так же класс печатать?

2021-10-17 13:15 UTC, rus-ai submitted a review, later dismissed

2021-10-17 15:10 UTC, stepanskryabin commented on README.md
> +```
Добавить cmd

2021-10-17 15:10 UTC, stepanskryabin commented on README.md
> +```
тут тоже cmd

2021-10-17 15:16 UTC, stepanskryabin commented on README.md
> +### Клонирование репозитория на локальный компьютер
Лучше полностью скопирую такое же описание с morelia_server там процедура форка описана хорошо.

2021-10-17 15:18 UTC, stepanskryabin commented on README.md
> +pipenv install --dev --ignore-pipfile
Эта команда аналогична команде выше (67 строка) только с установкой зависимостей из раздела dev-packages файла Pipfile только вот в описании про это ни одного слова. Надо добавить пояснения.

2021-10-17 15:24 UTC, stepanskryabin commented on main.py
> +            logger.info(f"background color: { background_color }")
лишние пробелы в фигурных скобках, до и после имени объекта

2021-10-17 15:30 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +        logger.info("add new chat " + new_chat_item)
@NekrodNIK А зачем на уровне INFO нам информация о классе? Я думаю на таком уровне достаточно информации что произошло, а на уровне DEBUG можно указать имя класса и какие-то ещё параметры.

P.S. а для лучшей читаемости я бы у класса ChatItem переопределил встроенный метод __repr__

2021-10-17 15:35 UTC, stepanskryabin commented on modules/logging.py
> +def set_logger_setting():
Я так понимаю ты будешь дописывать функцию для того чтобы с помошью нее устанавливать уровни логирования?

2021-10-17 15:39 UTC, stepanskryabin commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
Сложение строк через плюс эхто нехороший паттерн. При сложении двух первых строк интерпретатор создает объект в памяти куда складывает результат сложения, для сложение нового объекта и последней строки в памяти создается ещё один объект куда интерпретатор кладёт получившийся объект, итого в памяти пять объектов. лучше делай через метод .join объекта с типом str() либо подгружай строку из конфига.

2021-10-17 15:40 UTC, stepanskryabin commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
для закрывающего тего можно просто писать </>

2021-10-17 15:42 UTC, stepanskryabin commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
думаю в логах первым должно идти время, а не уровень

2021-10-17 15:44 UTC, stepanskryabin commented on modules/logging.py
> +        enqueue=True
Добавь сразу настройки ротации и сжатия.

2021-10-17 15:47 UTC, stepanskryabin commented on main.py
>          text_css = file.read()
Тут уже претензия не к этому ПР: если файла нет приложение не запустится, причём пользователю вообще ничего не сообщается. Надо исправить.

2021-10-17 15:48 UTC, stepanskryabin commented on main.py
>          text_css = file.read()
вот трэйсбэк:
```python
INFO | 2021-10-17 18:46:09.226Traceback (most recent call last):
 |   File "D:\code\morelia_client_qt\run_client.py", line 8, in <module>
Start client
    window = MainWindow()
  File "D:\code\morelia_client_qt\main.py", line 24, in __init__
    self.setColorTheme()
  File "D:\code\morelia_client_qt\main.py", line 33, in setColorTheme
    file = open(path.join("scss", "styles.scss"), "r")
FileNotFoundError: [Errno 2] No such file or directory: 'scss\\styles.scss
```

2021-10-17 15:50 UTC, NekrodNIK commented on main.py
>          text_css = file.read()
Понятно

2021-10-17 15:53 UTC, stepanskryabin commented on main.py
> +            logger.info("set custom color theme")
Тут надо уровень менять с INFO на DEBUG.

2021-10-17 15:54 UTC, stepanskryabin commented on main.py
> +            custom_theme = True
Вообще не нравится мне этот иф-иф-иф...но ничего хорошего предложить пока не могу.

2021-10-17 15:55 UTC, stepanskryabin requested changes
Так то всё нормально, но некоторые места надо поправить.

2021-10-17 16:14 UTC, NekrodNIK commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
Не знаю, мне так больше нравится по виду, вот и поставил

2021-10-17 16:15 UTC, NekrodNIK commented on main.py
> +            custom_theme = True
Самому не нравится, придумаю замену - перепишу

2021-10-17 16:24 UTC, stepanskryabin commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
Ладно ладно, не пройдёт и пары недель как поменяешь, причём сам )))

2021-10-18 14:06 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +        logger.info("add new chat " + new_chat_item)
Позже - да превратим, просто на данном этапе было не нужно, вот пока и так и будет

2021-10-18 14:07 UTC, NekrodNIK commented on README.md
> +```
Готово

2021-10-18 14:09 UTC, NekrodNIK commented on README.md
> +```
Готово

2021-10-18 14:17 UTC, NekrodNIK commented on README.md
> +### Клонирование репозитория на локальный компьютер
Готово

2021-10-18 14:26 UTC, NekrodNIK commented on README.md
> +pipenv install --dev --ignore-pipfile
Готово

2021-10-18 14:28 UTC, NekrodNIK commented on main.py
> +            logger.info(f"background color: { background_color }")
Готово

2021-10-18 14:34 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +        logger.info("add new chat " + new_chat_item)
Готово

2021-10-18 14:35 UTC, NekrodNIK commented on modules/logging.py
> +def set_logger_setting():
Да, но на данный момент достаточно и того, что есть

2021-10-18 14:40 UTC, NekrodNIK commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
Готово

2021-10-18 14:41 UTC, NekrodNIK commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
Так, посмотрел я на следующий день и понял, что ты был прав.

2021-10-18 14:44 UTC, NekrodNIK commented on modules/logging.py
> +            "<lvl>{level}</lvl>" +
Готово

2021-10-18 14:48 UTC, NekrodNIK commented on modules/logging.py
> +        enqueue=True
Готово

2021-10-18 14:48 UTC, NekrodNIK commented on main.py
>          text_css = file.read()
Позже поправлю

2021-10-18 14:50 UTC, NekrodNIK commented on main.py
> +            logger.info("set custom color theme")
пока уровень дебаг трогать не будем. Пока не принципиально

2021-10-18 15:03 UTC, stepanskryabin commented on modules/logging.py
> +        format=(str().join([
Поменяй:
```python
format=(str().join(["<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green>"," | <lvl>{level}</lvl> | ","<cyan>{message}</cyan>"]))
```
на
```python
format="".join(("<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green>", " | <lvl>{level}</lvl> | ", "<cyan>{message}</cyan>"))
```

2021-10-18 15:04 UTC, stepanskryabin requested changes
Ещё одна правка и всё.

2021-10-18 17:04 UTC, NekrodNIK commented on modules/logging.py
> +        format=(str().join([
Зачем? они возвращают одно и тоже - пустую строку

2021-10-18 17:43 UTC, NekrodNIK commented on modules/logging.py
> +        format=(str().join([
Понял, тут ещё замена list на tuple

2021-10-18 17:44 UTC, NekrodNIK commented on modules/logging.py
> +        format=(str().join([
Для уменьшения кол-ва используемой памяти

2021-10-18 17:48 UTC, NekrodNIK commented on modules/logging.py
> +        format=(str().join([
Готово. С str() на "" поменял только по тому что короче получается

2021-10-18 18:00 UTC, stepanskryabin approved these changes

2021-10-18 18:18 UTC, merged