Добавлено отображение данных из бд
MoreliaTalk/morelia_client_qt pull request #25
Opened 2021-12-10 03:14 UTC by NekrodNIK

Изменения:
1. Добавлено отображение чатов и сообщений из бд
2. Добавлено отображение сообщений по нажатию по карточке чата
3. Добавлена подсветка при hover и selected карточки чата
4. Выполнен переход на PySide6
5. Другие мелкие изменения

2021-12-10 11:05 UTC, stepanskryabin requested changes
Требуются небольшие изменения.

2021-12-10 11:05 UTC, stepanskryabin commented on interfaces/chats_controller.py
> +        new_chat_item = ChatItem(self.signals, uuid, chatName, lastMessageText, image)
Тут бы определится с переносом строк в параметрах функкции add_chat. Выше переносятся построчно, в этом месте всё в одну строку.

2021-12-10 11:05 UTC, stepanskryabin commented on interfaces/message_controller.py
> +        list_messages = list(self.MainWindow.db.list_messages(
Очень длинная строка получается, может лучше пробрасывать экземпляр класса Clientdb в класс MessageController?

2021-12-10 11:05 UTC, stepanskryabin commented on interfaces/message_controller.py
> +        list_messages = list(self.MainWindow.db.list_messages(
ну к остальным местам, где ты обращаешься к базе данных, такой же вопрос.

2021-12-10 11:05 UTC, stepanskryabin commented on interfaces/message_controller.py
> +        messages: List[MessageItem]
Это лишнее:
```python
messages: List[MessageItem]
```

2021-12-10 11:05 UTC, stepanskryabin commented on interfaces/message_controller.py
> +        for mes in messages:
А если messages будет пустым?

2021-12-10 11:05 UTC, stepanskryabin commented on main.py
> +    def connect_to_db(self):
Думаю лучше создавать объект класса Clientdb вне класса MainWindow и после передавать в MainWindow, таким образом точка подключения к БД будет одна.

2021-12-10 11:05 UTC, stepanskryabin commented on main.py
> +        list_flow: typing.List[models.Flow] = self.db.list_flow()
Может лучше так:
```python
list_flow: List[Flow] = self.db.list_flow()
```

А выше просто импортнуть:
```python
from typing import List
from models import Flow
```

2021-12-10 11:05 UTC, stepanskryabin commented on modules/database/clientdb.py
> +    def check_db_tables_created():
А зачем такой метод нужен? Ведь при создании таблиц в БД метод create_db создаёт таблици только при их отсутствии.

2021-12-10 11:07 UTC, NekrodNIK commented on modules/database/clientdb.py
> +    def check_db_tables_created():
То есть каждый раз создавать таблицы? Может проверить и только тогда?

2021-12-10 11:11 UTC, stepanskryabin commented on modules/database/clientdb.py
> +    def check_db_tables_created():
я думаю в main.py создавать экземпляр класса Clientdb и сразу выызывать метод create_db() а так как в этом методе идёт проверка на уже созданные таблицы в БД то задвоения не произойдёт.

2021-12-10 11:16 UTC, NekrodNIK commented on modules/database/clientdb.py
> +    def check_db_tables_created():
Ладно, сделаю

2021-12-10 12:36 UTC, NekrodNIK commented on interfaces/chats_controller.py
> +        new_chat_item = ChatItem(self.signals, uuid, chatName, lastMessageText, image)
В коротких функциях смотрится многострочная конструкция уродливо, а в длинных - как раз

2021-12-10 12:39 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        list_messages = list(self.MainWindow.db.list_messages(
Да, при рефакторинге так и сделаю(вместе с тестами).

2021-12-10 13:08 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        messages: List[MessageItem]
Готово

2021-12-10 13:35 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        for mes in messages:
То он просто не попадёт в for и всё. Пустой - значит не будет перебирать

2021-12-10 13:35 UTC, NekrodNIK commented on main.py
> +    def connect_to_db(self):
Да, согласен.

2021-12-10 13:36 UTC, NekrodNIK commented on main.py
> +        list_flow: typing.List[models.Flow] = self.db.list_flow()
Не, лучше конкретнее указывать

2021-12-10 13:39 UTC, NekrodNIK commented on modules/database/clientdb.py
> +    def check_db_tables_created():
Готово

2021-12-10 17:06 UTC, stepanskryabin requested changes
Последний момент остался (с импортом).

2021-12-10 17:06 UTC, stepanskryabin commented on main.py
> +    def connect_to_db(self):
Тогда поправь сразу.

2021-12-10 17:06 UTC, stepanskryabin commented on main.py
> +        list_flow: typing.List[models.Flow] = self.db.list_flow()
просто при импортировании конкретных классов, меньше памяти используется

2021-12-10 17:47 UTC, NekrodNIK commented on main.py
> +        list_flow: typing.List[models.Flow] = self.db.list_flow()
Ладно, уговорил

2021-12-10 17:48 UTC, NekrodNIK commented on main.py
> +    def connect_to_db(self):
Да времени мало сегодня, либо пулл реквест растягиваем на неделю - либо на потом

2021-12-10 17:54 UTC, stepanskryabin approved these changes, later dismissed

2021-12-10 18:39 UTC, rus-ai reviewed
В целом все нормально, перед релизом надо бы метод в db переписать для больших объемов чатов, а сейчас хотя  бы цвет в константу спрячь.

2021-12-10 18:39 UTC, rus-ai commented on interfaces/message_controller.py
> +                chat.setStyleSheet("background-color: #424242")
Может не сейчас но в будущем - не хорошо цвета по коду разбрасывать, надо или из файла темы парсить или хотя бы константой оформить.

2021-12-10 18:39 UTC, rus-ai commented on modules/database/clientdb.py
> +        list_mes = list(self.list_messages(flow_id))
Тут не очень понравилось, мы загружаем все сообщения все 100000 и потом берем только последнее. Надо будет потом на SQL переписать что то типа
SELECT TOP 1  * from messages WHERE message.flow_id = flowid ORDER BY message.time DESC

2021-12-10 18:40 UTC, rus-ai commented on modules/database/clientdb.py
> +        list_mes = list(self.list_messages(flow_id))
Можно даже на меня ишью повесить раз я в базе не предусмотрел.

2021-12-10 18:42 UTC, rus-ai requested changes

2021-12-10 18:42 UTC, rus-ai commented on main.py
> +            lastMessage = self.db.get_last_message(flow.uuid)
Хотя погоди! А зачем? У меня из БД уже возвращало для каждого flow последнее собщение. И общее число сообщений. Зачем заново запрашивать?

2021-12-10 18:51 UTC, rus-ai requested changes

2021-12-10 18:51 UTC, rus-ai commented on modules/database/clientdb.py
> +        db_query = models.Message.selectBy(flow=flow_id).orderBy("time")
Здесь минус был чтобы сообщения внутри оного чата в обратном порядке из базы извлеклись, и первое будет сообщение с максимальным временем, поэтому минус. А в таком виде функция будет возвращать для каждого чата не последнее а первое сообщение.

2021-12-10 18:53 UTC, rus-ai commented on modules/database/clientdb.py
> +        list_mes = list(self.list_messages(flow_id))
Если учитывать следующий мой комментарий то вообще функция ненужная.

2021-12-11 06:29 UTC, NekrodNIK commented on interfaces/message_controller.py
> +                chat.setStyleSheet("background-color: #424242")
Да я знаю, это костыль. Через главный css файл оно не захотело работать.

2021-12-11 06:30 UTC, NekrodNIK commented on main.py
> +            lastMessage = self.db.get_last_message(flow.uuid)
Н-да, надо исправить

2021-12-11 06:30 UTC, NekrodNIK commented on modules/database/clientdb.py
> +        list_mes = list(self.list_messages(flow_id))
Удалю

2021-12-11 06:32 UTC, NekrodNIK commented on modules/database/clientdb.py
> +        db_query = models.Message.selectBy(flow=flow_id).orderBy("time")
А добавление в чат идёт в каком порядке? Правильно, с первого. Иначе придётся порядок инвертировать уже в контроллере сообщений

2021-12-11 06:35 UTC, rus-ai commented on modules/database/clientdb.py
> +        db_query = models.Message.selectBy(flow=flow_id).orderBy("time")
Сортировка не по id а по времени. Мало ли вдруг добавили сначала последние 1000 сообщений, а потом при прокрутке вверх докачали из базы. Поэтому нужно отсортировать по убыванию времени и взять первое. Юнит тест это проверяет.

2021-12-11 06:37 UTC, NekrodNIK commented on modules/database/clientdb.py
> +        db_query = models.Message.selectBy(flow=flow_id).orderBy("time")
Ладно перепишу

2021-12-15 02:46 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        list_messages = list(self.MainWindow.db.list_messages(
Готово

2021-12-15 02:50 UTC, NekrodNIK commented on main.py
> +    def connect_to_db(self):
Готово

2021-12-15 02:50 UTC, NekrodNIK commented on main.py
> +        list_flow: typing.List[models.Flow] = self.db.list_flow()
Готово

2021-12-15 08:17 UTC, NekrodNIK commented on main.py
> +            lastMessage = self.db.get_last_message(flow.uuid)
Готово

2021-12-15 08:25 UTC, NekrodNIK commented on modules/database/clientdb.py
> +        db_query = models.Message.selectBy(flow=flow_id).orderBy("time")
гтово

2021-12-19 06:33 UTC, stepanskryabin requested changes
Внести небольшие правки и будет аппрув.

2021-12-19 06:33 UTC, stepanskryabin commented on interfaces/message_controller.py
> +        ))))
Очень многословная конструкция. Предлагаю написать отдельный метод для класса ClientDB чтобы отказаться от двух методов db.list_message и db.get_flow_id_by_uuid. При этом новый метод может сразу выдавать на выходе перевёрнутый кортеж.

2021-12-19 06:33 UTC, stepanskryabin commented on main.py
> +        list_flow: List[Flow] = self.db.list_flow()
Указание на тип можно убрать, т.к. при присваивании у объекта list_flow автоматом устанавливается тип

2021-12-19 06:33 UTC, stepanskryabin commented on main.py
> +        list_flow: List[Flow] = self.db.list_flow()
ну и соответственно импорт Flow можно будет убрать

2021-12-19 06:33 UTC, stepanskryabin commented on tests/lib_for_tests.py
> +
пустота...

2021-12-19 06:33 UTC, stepanskryabin commented on main.py
> +    def load_font(self):
Тут, кстати, Пайчарм предлагает в статикметод переделать. Или у тебя в планах динамическая подгрузка шрифтов?

2021-12-19 06:33 UTC, stepanskryabin commented on tests/test_chat_controller.py
>      def test_add_chat_nikname(self):
Очепятка, лучше так:
```python
def test_add_chat_nickname(self):
```

2021-12-19 06:37 UTC, NekrodNIK commented on main.py
> +    def load_font(self):
Ну предлагает и предлагает. Да знаю я, что он не со своим объектом взаимодействует, а с qt приложением. Ну и что?

2021-12-19 06:37 UTC, NekrodNIK commented on tests/test_chat_controller.py
>      def test_add_chat_nikname(self):
Ага, вижу

2021-12-19 07:25 UTC, stepanskryabin commented on main.py
> +    def load_font(self):
Опять же вся разница в памяти, статикметоды дополнительной памяти не используют, но тут не критично.

2021-12-19 07:33 UTC, NekrodNIK commented on tests/lib_for_tests.py
> +
)))

2021-12-19 08:34 UTC, rus-ai requested changes

2021-12-19 08:34 UTC, rus-ai commented on modules/database/clientdb.py
> +import uuid
А мы это разве где то используем?

2021-12-19 08:34 UTC, rus-ai commented on interfaces/message_controller.py
> +        ))))
А зачем мы здесь разворачиваем? У меня метод базы изначально в обратном порядке и выдаёт - сортировка по времени в обратную сторону time-

db_query = models.Message.selectBy(flow=flow_id).orderBy("-time")

2021-12-19 13:50 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        ))))
А перебираем-то мы с первого! То бишь по времени должно быть в порядке возрастания. Я минус убирал, но rus-ai, ты сказал вернуть как было, вот и вылезла сия абракодабра

2021-12-19 13:52 UTC, rus-ai commented on interfaces/message_controller.py
> +        ))))
Не правда, ты минус убирал в list_flow а не в list_message

2021-12-19 13:55 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        ))))
Значит путаю. Завтра разберусь, а то хоть сегодня и выходной, но дел у меня оказалось по горло

2021-12-19 13:57 UTC, NekrodNIK commented on main.py
> +        list_flow: List[Flow] = self.db.list_flow()
Готово

2021-12-19 13:57 UTC, NekrodNIK commented on tests/lib_for_tests.py
> +
Готово

2021-12-19 13:59 UTC, NekrodNIK commented on main.py
> +    def load_font(self):
Готово

2021-12-19 14:01 UTC, NekrodNIK commented on tests/test_chat_controller.py
>      def test_add_chat_nikname(self):
Готово

2021-12-19 14:02 UTC, rus-ai commented on interfaces/message_controller.py
> +        ))))
Ну и тогда функцию list- messages переписать так что бы она вместо uuid принимала id
Я когда писал не знал как будет удобнее её с каким аргументом вызывать.

2021-12-21 11:45 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        ))))
> Не правда, ты минус убирал в list_flow а не в list_message

Пролистай вверх, там list_message

2021-12-21 11:46 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        ))))
https://github.com/MoreliaTalk/morelia_client_qt/pull/25#discussion_r766907300

2021-12-21 14:10 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        ))))
Готово

2021-12-21 14:12 UTC, NekrodNIK commented on modules/database/clientdb.py
> +import uuid
Готово

2021-12-21 14:45 UTC, rus-ai requested changes
Мне реверс не нравится, а в остальном всё отлично.

2021-12-21 14:45 UTC, rus-ai commented on interfaces/message_controller.py
> +        messages_tuple.reverse()
Блин, что то не то, почему мы от reverse не избавились? Вроде из базы в прямом порядке сортировки и в обратном пытаемся, а после получения снова приходится разворачивать?

2021-12-21 14:51 UTC, NekrodNIK commented on interfaces/message_controller.py
> +        messages_tuple.reverse()
ГОТОВО

2021-12-21 14:56 UTC, rus-ai approved these changes
У меня больше замечаний нет. Супер, почти готовый клиент.

2021-12-21 14:59 UTC, NekrodNIK commented
> У меня больше замечаний нет. Супер, почти готовый клиент.

Поправочка - почти готовый ui клиента. Это довольно лёгкая часть, самое интересное ещё впереди

2021-12-21 15:02 UTC, rus-ai commented
> > У меня больше замечаний нет. Супер, почти готовый клиент.
> 
> Поправочка - почти готовый ui клиента. Это довольно лёгкая часть, самое интересное ещё впереди

Ну по крайней мере можно превью версией уже хвастататься даже без сети. Для презентации достаточно)

2021-12-21 15:09 UTC, NekrodNIK commented
> > > У меня больше замечаний нет. Супер, почти готовый клиент.
> > 
> > 
> > Поправочка - почти готовый ui клиента. Это довольно лёгкая часть, самое интересное ещё впереди
> 
> Ну по крайней мере можно превью версией уже хвастататься даже без сети. Для презентации достаточно)

Для презентации - да. Для того, что бы появились пользователи и комьюнити - пока нет.

2021-12-21 17:23 UTC, stepanskryabin approved these changes

2021-12-21 17:32 UTC, merged