Develop login dialog
MoreliaTalk/morelia_client_qt pull request #28
Opened 2021-12-25 17:44 UTC by rus-ai

Добавлен модальный диалог для запроса логина и пароля для подключения к серверу или данных для регистрации. 

Диалог можно закрыть кнопкой Cancel, стандартной кнопкой окна закрыть или нажатием кнопки Escape

При нажатии кнопки Ok (кнопка по умолчанию, так же срабатывает от Enter при нахождении фокуса ввода в любом виджете кроме кнопок) происходит проверка что обязательные поля заполнены, и если да то так же диалог закрывается. В противном случае незаполненным полям устанавливается динамическое свойство wrongInput которому в стиле можно задать изменение внешнего вида.

После обработки диалога в функции return_result() можно получить результат выполнения в формате именованного кортежа (action: Cancel, Login, Register в зависимости от нажатой кнопки или активной вкладки). Кроме action кортеж может содержать поля login, password, username, email.

Closes #16

2021-12-25 19:55 UTC, stepanskryabin requested changes
Убрать дублирование кода.

2021-12-25 19:55 UTC, stepanskryabin commented on interfaces/login.py
> +    @staticmethod
login.py после 75 строчки и main.py после 52 строчки один к одному (ну или почти) надо что-то придумать, чтобы не дублировать код.

2021-12-25 23:49 UTC, rus-ai commented on interfaces/login.py
> +    @staticmethod
Согласен, код не завязан на классы. Вынес его в в модуль interface.helpers оттуда любое окно сможет вызвать, но модуль main.py пока не трогаю, вижу @NekrodNIK в своей ветке  с ним активно работает, чтобы не вызвать конфликта.

2021-12-26 00:12 UTC, rus-ai commented
Добавил необязательные параметры login и password в конструктор диалога, для клиента хорошо бы сохранять имя пользователя между запусками (или иметь опцию "чужой компьютер" чтобы не сохранять), так же и для сохранения пароля если он будет храниться в plain-text (если же будет использоваться password manager то сюда можно передать звездочки, чтобы пользователь видел что пароль уже сохранен).

2021-12-26 05:32 UTC, stepanskryabin approved these changes, later dismissed

2021-12-27 04:50 UTC, NekrodNIK requested changes
Поправить пару мелочей и всё

2021-12-27 04:50 UTC, NekrodNIK commented on interfaces/helpers.py
> +    return text_css
А зачем сей файл вообще нужен? Согласен, что load_fonts не взаимодействует с окном, и его можно вынести. Но зачем его выносить в отдельный файл? А set_color_theme вообще устанавливает стили для именно MainWindow, и нельзя их разделять.

2021-12-27 04:50 UTC, NekrodNIK commented on run_client.py
> +    sys.exit(app.exec())
Ну пихать запуск диалога в run_client.py не стоило. Если уж и надо посмотреть на диалог в отдельности, то можно было это добавить в конец файла с кодом диалога.

2021-12-27 15:07 UTC, rus-ai commented on run_client.py
> +    sys.exit(app.exec())
Я же не знал где ты будешь вызывать. Убрал вызов, оставил только в самом модуле - при непосредственном его запуске.

2021-12-27 15:32 UTC, rus-ai commented on interfaces/helpers.py
> +    return text_css
set_color_theme придется вызывать для каждого окна, я проверил - дочерние окна главного окна без этого показывают в стандартном стиле.
Возможно придется в последствии вынести часть подготовительных функций и вызывать один раз, а стиль применять уже с готовыми переменными, так что файл будет рости.

2021-12-28 04:59 UTC, NekrodNIK commented on interfaces/helpers.py
> +    return text_css
в общем оставляй пока как есть, сам сейчас решаю эту проблему на своей ветви

2021-12-28 05:00 UTC, NekrodNIK approved these changes

2021-12-28 11:22 UTC, merged